### ISSUE TITLE
Test dependencies should be devDependencies not peerDependencies

### ISSUE THREAD

**Issue by dieseldjango** [mac-s-g/react-json-view#108]
I'm trying out your excellent package, and getting a lot of peer dependency warnings on package install for stuff like, chai, nyc, istanbul, etc. I'm not sure why these are listed as peerDependencies when they are presumably needed only for development. It would help to cut down the noise if those were moved where they belong under devDependencies.

**Comment by mac-s-g** [comment]
you are absolutely right.  thanks for pointing that out.  i will update as soon as I have a chance.

**Comment by mac-s-g** [comment]
I tightened up the build quite a bit with #110 .
that includes the update you requested @dieseldjango .

I'll update this thread when the updates are merged and published to npm.

**Comment by mac-s-g** [comment]
updated and published to npm v 1.12.2
