### ISSUE TITLE
Empty items shouldn't be expandable

### ISSUE THREAD

**Issue by KieranWebber** [mac-s-g/react-json-view#111]
Empty arrays and objects should not be expandable. It adds excess height to the tree and clutters the UI. This is especially relevant on a tree that is pre expanded.

Removing the dots from inside the curly braces or brackets ([] or {}) in the UI and making it unexapndable will much more clearly communicate the fact its empty.

<img width="322" alt="screen shot 2017-09-07 at 17 45 03" src="https://user-images.githubusercontent.com/1757041/30174885-7763516c-93f4-11e7-8ed7-21f1badb1a42.png">

The top is an example on how I suggest it should be displayed and the bottom is how it is displayed currently.

**Comment by mac-s-g** [comment]
I agree.  I'll get a PR up for this as soon as I have time.

**Comment by mac-s-g** [comment]
updated with #113 and published to [npm under 1.12.3](https://www.npmjs.com/package/react-json-view)

`+ react-json-view@1.12.3`

let me know if that meets your expectation.
