### ISSUE TITLE
Callback feature request

### ISSUE THREAD

**Issue by sksbtps** [mac-s-g/react-json-view#116]
If the json is big It takes some time to load. So, can we have a callback once the data is ready to show?

**Comment by mac-s-g** [comment]
what do you mean by "ready to show"?

would behavior be any different than wrapping the component and using the `componentDidMount` method?

**Comment by mac-s-g** [comment]
I'm closing this for now because I think you can create this behavior by using react's built-in lifecycle methods on top of RJV

for example:
```
class MyComponent extends React.Component {

    render() {
        return <ReactJsonView src={this.props.src}>
    }

    componentDidMount() {
        //here is your callback
    }

}
```

if you don't think this is a valid solution, let me know and i'm happy to open this back up.

**Comment by sksbtps** [comment]
Actual problem is, If your json is big, It will take approx 2 secs before opening. Now, for those 2 sec you don't know whether it is working or not. So, if you want to wrap this component (JSON VIEWER) in a ant design Modal and show it then the modal takes 2 sec to open up. So, I wanted to know If there is anyway, to know if JSON viewer is ready to render the data so that till then I can show the modal with a loading icon.

**Comment by mac-s-g** [comment]
I was thinking you wanted to show some sort of loader.

you're going to need some asynchronous rendering behavior so that you can 

there's probably a better solution than setTimeout for async rendering, but you can try something like this:

```
class MyComponent extends React.Component {

    state = {
        rjv_component: false
    }

    componentWillMount() {
        // there's probably a better way than setTimeout for non-blocking rendering
        const TIMEOUT = 10 // wait 10 ms
        setTimeout(() => {
            this.setState({
                rjv_component: <ReactJsonView src={this.props.src} />
            })
        }, TIMEOUT)
    }

    render() {
        return <div>
            {this.getJsonOrLoader()}
        <div />
    }

    getJsonOrLoader = () => {
        const {rjv_component} = this.state
        if (rjv_component === false) {
            return <MyLoader />
        } else {
            // component was rendered and stored to this var
            return rjv_component
        }
    }

}
```
