### ISSUE TITLE
Request supporting on 'onSelect' and 'onCopy' events.

### ISSUE THREAD

**Issue by zheeeng** [mac-s-g/react-json-view#117]
As title as requested, hope we can pass callbacks to handle selecting the items of JSON object and success copied data.

**Comment by mac-s-g** [comment]
I can definitely add an `onCopy` event.

can you give me more info on what you mean by `onSelect`?

**Comment by zheeeng** [comment]
`onSelect` cloud be also named as `onClick` or `onDataClick`. When we click a data, it triggers a callback. I'm writing tool displaying JSON object which may contain normal URL, image URL, data array, we can pick the data and then open a modal to choosing a data parser to handle URL or data. Nowadays the workaround is using the `onDelete` callback which always returns false to simulate the `onClick`, and I have to overwrite the styles of `click-to-remove-icon`(change it to a custom icon) and `validation-failure`(display: none), and I have to click the fake `parse icon`.

**Comment by mac-s-g** [comment]
i posted #118 

that add support for callback functions to be specified to the `enableClipboard` prop.

from the PR:
`enableClipboard` prop now supports a callback function rather than just boolean `true` or `false`.

```
enableClipboard={(copy) => {
    // copy object is passed to callback
    // copy object contains `src`, `namespace`, and `name` attributes
    console.log(copy) 
}}
```

I'll update here when that is merged and published to NPM.

**Comment by mac-s-g** [comment]
#118 is merged and updated component is published to [npm](https://www.npmjs.com/package/react-json-view) under `react-json-view@1.12.5`

**Comment by mac-s-g** [comment]
I'll work on adding an `onSelect` so you don't have do use so many workarounds!

**Comment by zheeeng** [comment]
@mac-s-g Thanks!

**Comment by mac-s-g** [comment]
added `onSelect` with #119 

I'll update when that's published to npm

to make the ux feel smooth, i had to replace `double-click` edit shortcut with `ctrl+click`. 

that's because `single-click`ing a value now triggers `onSelect` (when it's defined)

you can get more info about that in the "keyboard shortcuts" list at the bottom of the [demo page](https://mac-s-g.github.io/react-json-view/demo/dist/)

**Comment by mac-s-g** [comment]
published updates to [npm](https://www.npmjs.com/package/react-json-view) under `react-json-view@1.13.0`

you're my only `onSelect` user so far, so let me know if that meets your requirements.

**Comment by zheeeng** [comment]
Wonderful! I will update my feature implementation this afternoon!
