### ISSUE TITLE
cost too much time when nesting json data

### ISSUE THREAD

**Issue by secreter** [mac-s-g/react-json-view#120]
When json data nesting a lot ,the function  setState ({json}) will spend a lot of time,even more few seconds,thats should be a bug

**Comment by mac-s-g** [comment]
can you post more info about this?

what is the src you're passing in?

how can I replicate?

**Comment by mac-s-g** [comment]
I'm gonna close this for now.  I'm happy to open it back up if I can get more information describing the issue.
