### ISSUE TITLE
Is there a way to display line numbers?

### ISSUE THREAD

**Issue by LaurieSReynolds** [mac-s-g/react-json-view#126]
Thank you for a great component!    Is there currently a way to display line numbers?

Example....
```
1 . {
2 .     "check-coverage": true,
3 .     "per-file": false,
4 .     "all": true,
5 .     "lines": 80,
6 .     "statements": 80,
7       "functions": 80,
8      "branches": 80,
9      "require": [
10         "babel-register",
11          "babel-polyfill"
12      ],
13 .   "reporter": [
14         "lcov",
15         "html",
16         "text"
17     ],
18   "cache": true,
19   "report-dir": "./coverage"
20 }
```

**Comment by mac-s-g** [comment]
there's not currently support for line numbers but that's a great idea!  :+1: 

i'll tag this as "feature request" and comment when after I can check it out.

**Comment by LaurieSReynolds** [comment]
Thank you!

**Comment by mac-s-g** [comment]
closing this for now as it hasn't gathered additional feedback and does not fit the current direction for source code

**Comment by TatyanaVl** [comment]
I would be nice to have this functionality available.

**Comment by rohith2710** [comment]
@mac-s-g , is line numbers feature implemented?
