### ISSUE TITLE
Has anyone done alternate row shading or what can I use to select for alternate row shading

### ISSUE THREAD

**Issue by LaurieSReynolds** [mac-s-g/react-json-view#127]
We would like to shade alternate rows and I am trying to determine what selectors I can use for this.

**Comment by mac-s-g** [comment]
sounds like you want to get that "text editor" feel.  are other people interested in that style?

after playing around with the html a bit, i can see that this would take some structural work (and so would line numbers).

i was able to fake it by setting constant line height and applying a background gradient, but this caused other behavioral problems and unexpected consequences.

i just tried background css along the lines of:
```
.object-container {
    background: repeating-linear-gradient(to bottom, #2b2b2b, #2b2b2b 20px, #333 20px, #333 40px);
}
```
(you can see how i faked lines)
![highlight-line-attempt](https://user-images.githubusercontent.com/4097374/31974365-36853082-b8e0-11e7-8b20-5ffd140ab596.png)

i think the right way to support both features would be to take a line-by-line approach to rendering.  that's in contrast to the parent->child component structure currently in place.  

maybe there's a way to get the best of both.

**Comment by LaurieSReynolds** [comment]
Thank you!  We would like line numbers and shading to make it easier when viewing two json files side by side and comparing them.

**Comment by mac-s-g** [comment]
closing this for now as it has not gathered addl feedback and does not fit the current direction for source code
