### ISSUE TITLE
Lowercase True/False

### ISSUE THREAD

**Issue by JasonEtco** [mac-s-g/react-json-view#128]
Hey there! Dig the lib, but there's this one nitpick I have. The boolean types (true/false) are title-cased, and I can't think of a reason why, since in JS itself it's all lowercase (and obviously in the JSON objects this component would receive).

I can open up a PR to change it if you'd like 👍 

https://github.com/mac-s-g/react-json-view/blob/15f00b4966a6f608496ebd830f4227d1b4aa3b37/src/js/components/DataTypes/Boolean.js#L16

**Comment by mac-s-g** [comment]
i posted #130 to update patch version so that changes can be published to npm.  i'll update once that's published.

**Comment by JasonEtco** [comment]
Cool, thanks for getting it it so quickly!

**Comment by mac-s-g** [comment]
np!

published `+ react-json-view@1.13.2` to [npm](https://www.npmjs.com/package/react-json-view)
