### ISSUE TITLE
Support custom "default" collapsing

### ISSUE THREAD

**Issue by Alxandr** [mac-s-g/react-json-view#137]
Currently, the collapsed property accepts either a bool or a number. It would be great if we could provide a function of the form `(path: string) => boolean` do decide what to collapse. Where it would typically be called with `.foo.bar` if I have an object structure like `{foo: {bar: {....}}}`. This way I would be able to create simple rules like "everything that starts with `_` should be collapsed.

For arrays the path should be `[2].bar` for instance.

**Comment by mac-s-g** [comment]
i think this is a great idea.  I'll tag this as "feature request".

**Comment by mac-s-g** [comment]
@Alxandr (also relevant for @ajbdev) I added a `shouldCollapse` callback method.

you now have full control over what fields are collapsed by default

```javascript
// collapse objects and arrays with length greater than 5
shouldCollapse={({src}) => Object.keys(src) > 5}

// collapse after depth 2
shouldCollapse={(namespace) => namespace.length > 2}

// collapse objects named "myObject"
shouldCollapse={({name}) => name == "myObject"}

// more in depth collapse logic
shouldCollapse={(field) => {}}
```

**Comment by mac-s-g** [comment]
now wondering if I should just combine callback support with the original `collapsed` prop...

**Comment by ajbdev** [comment]
This is great. Thanks for this!!
