### ISSUE TITLE
OnEdit: TypeError: [x] is not a function

### ISSUE THREAD

**Issue by liester** [mac-s-g/react-json-view#139]
Hello, 
  First, thank you for creating this library.  I'm hoping it saves me from building a custom json editing solution.  It looks like when 'OnEdit' of provided as a prop when you click on the value portion of a property (not object or array) an error is thrown.  
Below is from your demo site:
https://mac-s-g.github.io/react-json-view/demo/dist/
Based on the documentation's mention of double click opening the edit text area I suspect it may be that logic that isn't working.  Let me know if more information is required or if I'm just not doing it correctly.
![onediteror](https://user-images.githubusercontent.com/6137420/33959309-ba135ac0-e00c-11e7-9d9c-49750c087b6d.png)

**EDIT**
I was looking through the documentation and I saw there is one last 'on' command, 'onSelect'.  If I enable that along with the other 'on' commands I no longer get the error.  So good news I won't get hammered by my team for errors and I can still use the library.  I hope that information is helpful.

**Comment by mac-s-g** [comment]
thank you for reporting this.  I'm seeing the same error get thrown.  I'll investigate asap

**Comment by mac-s-g** [comment]
issue is resolved and published to [react-json-view v1.14.1](https://www.npmjs.com/package/react-json-view)
