### ISSUE TITLE
Copy to Clipboard for properties too

### ISSUE THREAD

**Issue by danie16arrido** [mac-s-g/react-json-view#141]
Can we have the option to enable Copy to clipboard for the properties value too within an object?
Currently it is enabled only for objects. 

![output-example-monokai-2](https://user-images.githubusercontent.com/26549236/34256455-5a942d26-e64d-11e7-8d29-74d1a6d00353.png)

**Comment by mac-s-g** [comment]
[I posted a PR](https://github.com/mac-s-g/react-json-view/pull/145) on the `copy-everything` branch.  

I'd want to remove code duplication and add some tests before merging.  

More importantly, I want to know if this is a feature that others are interested in adding.  The icons are adding up, and adding an additional icon to value hovers may feel overwhelming.  but if this is something that others would like to see, I'll clean up the PR and publish with a new version.

**Comment by mac-s-g** [comment]
published with [react-json-view@1.15.2](https://www.npmjs.com/package/react-json-view).
