### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by andreevich** [mac-s-g/react-json-view#157]
Is there support typescript definitions?

**Comment by mac-s-g** [comment]
There's not - and I'm honestly not sure how to go about implementing that.  It would be cool to get some help on this one.  I'll tag it with "help wanted".

**Comment by ChuckJonas** [comment]
I could maybe take this on when I have some free time

**Comment by mac-s-g** [comment]
@ChuckJonas that would be awesome!

**Comment by franklixuefei** [comment]
@ChuckJonas Have you had time to add the typings?

**Comment by franklixuefei** [comment]
Filed PR for this issue: #187
