### ISSUE TITLE
If my_json_object contains Moment.js object, it will crash

### ISSUE THREAD

**Issue by fanpaa** [mac-s-g/react-json-view#159]
**snapshot**:

![](http://p2.cdn.img9.top/ipfs/QmQohguW3CMQeHvExPpnmVxFVqrcFXohKuK9TqkAd8wzZE?2.png)

maybe  the **regex rule** reason?

**Comment by mac-s-g** [comment]
@fanpaa nice find.  and thanks for reporting it.  I can look into it as soon as I have some time.  I'm also happy to review and test pr's :)

**Comment by mac-s-g** [comment]
the parser is failing because the Moment class contains some `regexp` properties.
there's not currently support for `regexp` types.  

I'm working on adding that in now.  should have an updated package published in an hour or two.
