### ISSUE TITLE
 paste support

### ISSUE THREAD

**Issue by stxwd46** [mac-s-g/react-json-view#162]
rjv now support copy, but do you have a plan to support paste?

**Comment by mac-s-g** [comment]
@stxwd46 thanks for posting!  can you describe the idea a little more?  what would it mean to support paste?

**Comment by stxwd46** [comment]
for example，I copied a json from outside，and I want to paste directly into rjv

**Comment by mac-s-g** [comment]
@stxwd46  you should be able to paste in by enabling `onEdit` and `onAdd`.  you would have to click the button to either add or edit a value and then you can paste content in.

does that satisfy your use case?

**Comment by stxwd46** [comment]
`onAdd` can only paste a key, and `onEdit` can only paste a value. When I want to paste a whole json, it can not satisfy me.

**Comment by mac-s-g** [comment]
I'll leave this open in case others are also interested in the feature.  but I need a better idea of how this would actually work before I can think about implementing something.  
what would trigger a paste event?  ctrl+v anywhere on the rjv component?  where would json get posted?  can you highlight a value and paste into it?  
at a high level, you get the same functionality by: 
 * adding a key
 * editing the value 
 * and pasting content into the textarea
right?

**Comment by stxwd46** [comment]
I have an idea, rjv can add another mode like [monaco-editor](https://github.com/Microsoft/monaco-editor), and users can switch between two modes.
for example
A mode
![image](https://user-images.githubusercontent.com/7361933/35368769-f4110efa-01bf-11e8-9e81-919bfcb657cc.png)

B mode
![image](https://user-images.githubusercontent.com/7361933/35368778-fee391d6-01bf-11e8-9b64-3e312e94fadf.png)

Users can see the structure of JSON clearly and modify part of the data on A mode.
And users can free to modify the whole JSON on B mode. At the same time, we should have a format checks about JSON on B mode.

**Comment by mac-s-g** [comment]
Thanks again for the feedback.  I don't think the request fits the direction of this project, so I'm going to close this request.  I could see this being a feature for a higher order component that depends on RJV.  

Feedback is still welcome here from anyone interested in this type of functionality.
