### ISSUE TITLE
Not working with react-materialize

### ISSUE THREAD

**Issue by subhendukundu** [mac-s-g/react-json-view#168]
I am not sure if its an issue. I am just trying to render ``` <ReactJson src={src} /> ``` with a sample JSON. But the components are not rendering with react-materialize. 
Getting an error of ``` Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information. ```
Any idea how do I resolve it?

**Comment by mac-s-g** [comment]
that sounds a bit out of scope.  that's react grinding to a halt due to SOP/CORS violation.  
can you give me more info about what your source code looks like?

what is the value of `src` that you're passing to the RJV component?

**Comment by mac-s-g** [comment]
@subhendukundu gonna close this for now unless I get more info.  I'm doubting that this is an RJV issue.
