### ISSUE TITLE
OnEdit bug with es5 implementation

### ISSUE THREAD

**Issue by Rennzh** [mac-s-g/react-json-view#172]
I added the onEdit callback for examples but did not respond when I click check button
![tim 20180225014451](https://user-images.githubusercontent.com/9619419/36633293-b386787c-19cd-11e8-893d-ae83928d6094.png)

**Comment by mac-s-g** [comment]
@Rennzh thanks for reporting.  I will attempt to re-create the issue.

**Comment by mac-s-g** [comment]
@Rennzh I'm not having any issues when running tests locally - but I'm testing the jsx implementation.

I also see the [demo](file:///home/mac/dev/git/personal/react-json-view/demo/dist/index.html) appropriately logging to the console when I submit an edit.

can you give me more detail about your environment to help me recreate your issue?

**Comment by Rennzh** [comment]
@mac-s-g thank you for you response. I downloaded the demo folder and directly modified this file:[main.js](https://github.com/mac-s-g/react-json-view/blob/master/demo/dist/main.js), then I ran the index.html in chrome.
My encoding environment is win10,chrome64

**Comment by Rennzh** [comment]
@mac-s-g I found the reason: I ran the build script and use dist/main.js in test.html, but lifecircle did not fire when the component was mounted, so event listener has not been added

**Comment by Rennzh** [comment]
@mac-s-g It's wrong way to use in the test.html and I change the jsonView1 to below, it work well
```javascript
var jsonView1 = React.createElement(reactJsonView.default, {
    src: test_json,
    collapseStringsAfterLength: 18,
    onEdit: (edit) => {
      console.log('edit', edit);
      return true;
    }
});
ReactDOM.render(
    jsonView1,
    document.getElementById('example1')
);
```
