### ISSUE TITLE
Make `array-key` values toggleable

### ISSUE THREAD

**Issue by mcclayton** [mac-s-g/react-json-view#180]
Currently arrays are displayed with an array-key value, it would be great if this were something that could be toggled on and off via a prop so that we could display arrays as:
```
[
   "one", 
   "two",
   "three"
]
```
Instead of: 
```
[
   0: "one", 
   1: "two",
   2: "three"
]
```

**Comment by mac-s-g** [comment]
good idea, thanks for the feedback.  I'll tag this as a feature request.

**Comment by houshuang** [comment]
This would be very useful to us as well, came here looking for that. Thanks for a great component!

**Comment by imdanielsp** [comment]
@mac-s-g  Assuming this hasn't been resolved, I would like to make this change. I will send a PR soon.

**Comment by isaacgr** [comment]
Hoping this gets merged, as it would really clean up the data being displayed. Love the component!

**Comment by nick-cromwell** [comment]
This would be really great

**Comment by nick-cromwell** [comment]
@imdanielsp It appears @mac-s-g is looking for new maintainers of this repo. I'm not sure if you would be interested in that but I'm guessing it is unlikely this gets merged until a new maintainer is assigned.

**Comment by imdanielsp** [comment]
@nick-cromwell I would be happy to be a maintainer (I use this heavily 🙂). Where did you find out that @mac-s-g is looking for one?

**Comment by nick-cromwell** [comment]
@imdanielsp I saw it in #292 . I've just started using the library but it's excellent. Really great for custom API documentation.
