### ISSUE TITLE
collapseStringsAfterLength responsive display

### ISSUE THREAD

**Issue by mrchief** [mac-s-g/react-json-view#183]
Currently it requires a prop `collapseStringsAfterLength` with a fixed number to show ellipsis. This approach doesn't work well with responsive views. Is there way to make this number grow/shrink based on the viewport size?

**Comment by mac-s-g** [comment]
I think what you're looking for is more control over css.  You don't want to use `collapseStringsAfterLength` prop, you want to specify the text-overflow css attribute to improve how responsive your display is.  I'm gonna link this to #156 and close as duplicate.

Thanks for the feedback!  if you feel i'm misunderstanding the request feel free to post here and I can re-open.

**Comment by mrchief** [comment]
`text-overflow` is not of much help. It can only do clip/fade/ellipsis which is not what I want. I want the text to wrap, so that its still visible. Or if ellipsis are shown, at least the full text is visible with tooltip or something to that effect. 

#156 can only help applying additional styles but like I said, I'm not looking for simply applying styles.

**Comment by jdifeder** [comment]
After much CSS tweaking I was able to figure out a pretty simple workaround to make the text not wrap.
Hope this helps someone!

First, I rendered the `<ReactJson/> `in a `<div>` instead of a `<pre>` which got me halfway there.

The last change was CSS:

```
.variable-value {
  word-break: break-all;
}
```
