### ISSUE TITLE
string_number

### ISSUE THREAD

**Issue by mckennatim** [mac-s-g/react-json-view#195]
Ok so what is the json trick to have the editor read a number input as a string? In the demo adding a digit to "string_number" turns it into an int. quoting it like '12345' turns it into "'12345'"

**Comment by mac-s-g** [comment]
when editing, try clicking the top check mark instead of the one sitting next to `int 10`.

![top-check-mark](https://user-images.githubusercontent.com/4097374/41010721-1c02664e-68ee-11e8-956d-989c22180353.png)

does that solve your problem?

**Comment by mckennatim** [comment]
It was very clear once I dove in and put rjv in a project (for admins to set up config on IOT devices). To me now it is very intuitive and cool and easy to use.
