### ISSUE TITLE
[React 16.3+] [Proposal] Migrate to React 16.3+ new lifecycles.

### ISSUE THREAD

**Issue by franklixuefei** [mac-s-g/react-json-view#196]
I propose to make some changes to migrate the codebase to supporting the React 16.3+ new lifecycles. I can take a stab at it and send a PR.

**Comment by franklixuefei** [comment]
@mac-s-g I also want to confirm with you if it's okay to bump up the react peer dependency minimum version to 16.3.2?

**Comment by mac-s-g** [comment]
@franklixuefei I am 100% behind that!  thanks for contributing

**Comment by franklixuefei** [comment]
@mac-s-g Thanks Mac! I filed a PR #197 

Please don't be scared by how many lines of code I changed. I didn't change any of the logics, but just migrated to the new lifecycle hooks and removed some anti-patterns.

**Comment by franklixuefei** [comment]
Close due to #197
