### ISSUE TITLE
When the src prop is updated from parent component the edition is broken

### ISSUE THREAD

**Issue by vdelord** [mac-s-g/react-json-view#206]
I allow the user to select from different JSON templates and I display them in a ReactJson like that :

> contructor(props) {
> super(props)
> this.state = {
>   thejson: JSON.parse(initialJson)
> }
> ...
> this.setState({
>   thejson: JSON.parse(newJson)
> })
> ...
> <ReactJson src={this.state.thejson} onEdit={(edition)=>{return true}}/>

So when the state is updated the ReactJson component displays the new json BUT
when I edit a value in this new json, ReactJson tries to update the value on the first json ever displayed by the component since the first load of the page (let's call it initialJson).
Here is the 'edition' object when I display its content :

> {
>   existing_src: newJson
>   name: theKey
>   new_value: theEditedValue
>   ...
>   updated_src: initalJson[theKey] = theEditedValue
> }

I expect updated_src to be existing_src[theKey] = theEditedValue instead.

**Comment by vdelord** [comment]
I've fixed my issue by updating the ObjectAttributes with the new src property on componentDidUpdate.

> componentDidUpdate(prevProps, prevState) {
>         //reset key request to false once it's observed
>         if (prevState.addKeyRequest !== false) {
>             this.setState({
>                 addKeyRequest: false
>             });
>         }
>         if (prevState.editKeyRequest !== false) {
>             this.setState({
>                 editKeyRequest: false
>             });
>         }
>         if (prevProps.src !== this.state.src) {
>             ObjectAttributes.set(
>                 this.rjvId,
>                 'global',
>                 'src',
>                 this.state.src
>             );
>         }
>     }

I'm new to this so I post this comment before looking at how to propose a contribution to the project ;)

**Comment by mac-s-g** [comment]
@vdelord thanks for reporting the bug!

Can you post a PR with your changes?  
If you're comfortable doing that, I can review.  
Please bump the patch version in `package.json` with that.
That will make it easy for me to publish the fix.

**Comment by mac-s-g** [comment]
resolved by #208
