### ISSUE TITLE
src Change

### ISSUE THREAD

**Issue by YavuzMetin** [mac-s-g/react-json-view#210]
I just want to change the input json file as which file that user selected with some input button or something. Is there any way to do that?

**Comment by mac-s-g** [comment]
@YavuzMetin .  thanks for posting.  you should be able to change the src attribute and see changes rendered.  if you're having issues with that, I would recommend posting some example code so that someone can help you debug.

**Comment by YavuzMetin** [comment]
I don't have code right now but I think it's something like that:

import React, {Component} from 'react'
import ReactJson from 'react-json-view'

class App extends Component {
	constructor(props){
		super(props);
		this.handle = this.handle.bind(this);
	}
handle() {
	data = document.getElementById("myfile")
}
render() {
	var data;
	return(
		<div>
		<input type='file' name="myfile" onChange={this.handle}>
		<ReactJson src={data} />
		</div>
	)
}
}
export default App;


There can be some syntax problems but it's not the full code that I wrote. If you want to know more about it, I can send tomorrow. Good night :)
