### ISSUE TITLE
When copying to the clipboard, string-type value is enclosed in double quotes

### ISSUE THREAD

**Issue by skyoo2003** [mac-s-g/react-json-view#217]
I just want to get only a string value when copying to the clipboard. but, it's enclosed in double quotes. Is there any way to get it?

![bb](https://user-images.githubusercontent.com/9215745/44733615-ea1ff200-ab22-11e8-8fa7-42fcae31c7c5.jpeg)

`"test"` was saved in clipboard. but, I expected it to be a `test`

**Comment by skyoo2003** [comment]
@eyalap Cool. That's what I wanted!
Personally, I hope this work will be reflected in this project as well.

**Comment by jmburdette** [comment]
You can use the callback to remove the quotes and re-copy it to the clipboard:

<ReactJson
    enableClipboard={this.onCopy} />

    // override default behavior for copying to exclude double quotes.
    onCopy = (copy) => {
        const container = document.createElement('textarea')
        const val = copy.src

        container.innerHTML = typeof(val) === 'string' ? val : JSON.stringify(
            val,
            null,
            '  '
        )

        document.body.appendChild(container)
        container.select()
        // copy the same quote-less value back to the clipboard
        document.execCommand('copy')
        document.body.removeChild(container)
    }
