### ISSUE TITLE
React Json view gets moved when mouse overs json lines

### ISSUE THREAD

**Issue by srivathsa-kavirayuni** [mac-s-g/react-json-view#241]
In React JSON view, when pointer overs the json lines, producing extra line space between the mouse over line and below line, even though the styling is correct. Help me to get out of this.
Thanks.

![ezgif com-crop](https://user-images.githubusercontent.com/40168293/53004229-c21ca600-3456-11e9-89f3-2fad0db1c782.gif)

**Comment by seanes** [comment]
The icons (appearing on mouse over) are larger than the font-size and all items are aligned. If you increase the font-size, to e.g. 12px, on the component, this should not happen.

**Comment by srivathsa-kavirayuni** [comment]
Component uses font-size as `14px`.
Issue will resolve if I change the font-size to `30px` (which was used by copy svg icon).
`30px` is very large.

@seanes Is there any other solution?

**Comment by srivathsa-kavirayuni** [comment]
@seanes Is there any update for above query ?

**Comment by rogchap** [comment]
I used this instead of increasing the font size:
```css
.react-json-view svg {
    height: 0.9em !important;
}
```
