### ISSUE TITLE
Long string will overflow,even use collapse

### ISSUE THREAD

**Issue by shengbeiniao** [mac-s-g/react-json-view#244]
![image](https://user-images.githubusercontent.com/3301995/51970292-81fa8100-24b1-11e9-8108-d3cf54ebed92.png)

**Comment by ShunnyBunny** [comment]
@shengbeiniao I have the same issue, do you know of any quick fix?

**Comment by ShunnyBunny** [comment]
#240 
This issue seems to be duplicated. There is currently pull request on a fix.

.react-json-view {
    word-break: break-all;
}

seems to do the trick for me

**Comment by mac-s-g** [comment]
merged #218
