### ISSUE TITLE
when json property name is "length" will render failed

### ISSUE THREAD

**Issue by willcong** [mac-s-g/react-json-view#252]
![image](https://user-images.githubusercontent.com/9913266/54202900-03f7b400-450c-11e9-92d4-a06cd534efc0.png)
![image](https://user-images.githubusercontent.com/9913266/54202918-0fe37600-450c-11e9-8589-9bd841d2dc38.png)

**Comment by mac-s-g** [comment]
published to npm: `react-json-view@1.21.2`
