### ISSUE TITLE
long number display wrong

### ISSUE THREAD

**Issue by bing1021** [mac-s-g/react-json-view#280]
my version is `1.19.1`
here is my code 
```
import ReactJson from "react-json-view";

<ReactJson
     src={{
       count: 123456789987654321
     }}
      theme="monokai"
 />
```
![22d6f1dac662104b87bf93270b46973cf2000ba0](https://user-images.githubusercontent.com/13826594/76158746-15da5a00-6154-11ea-8ada-b8d03e272bb2.png)

the last number is 1, but the component displays 0!!!

**Comment by KiranGopalakrishnan** [comment]
JavaScript uses 64bit floating point numbers exclusively, Meaning there is no guarantee of precision for anything after 16 digits, you can pass in the value as a string instead

**Comment by mac-s-g** [comment]
thanks for the clarification @KiranGopalakrishnan
