### ISSUE TITLE
src not updating after setState

### ISSUE THREAD

**Issue by adamalexandru4** [mac-s-g/react-json-view#301]
I can't figure it out how to update the src prop when the parent state changed. I tried with hooks, React class component .. nothing works. 
Help me with a sample please.

**Comment by jldamas** [comment]
Try to collapse, then uncollapse it.  It seems to update the data when collapsed

**Comment by mac-s-g** [comment]
I'm not able to replicate.  You should be able to control src from a parent component (i just tested in development).
try upgrading to 1.20.3.  If you're still having an issue, share some more detail and I'll try to help you out.

**Comment by jzombie** [comment]
If I'm not mistaken, this issue could be related: https://github.com/mac-s-g/react-json-view/issues/227
