### ISSUE TITLE
enableClipboard callback does not returns correct Keys

### ISSUE THREAD

**Issue by 3wweiweiwu** [mac-s-g/react-json-view#305]
Hello,

In my case, I want to extract the JSON key by using copy feature. When I try to use that, I notice that the value in the namespace does not match what I expect. For example
{
  key1:8
  key2:[]
}

When I try to copy the value at key1, the namespace returns value [root]. The value is 8 though.

The funny thing is that when I copy the value at key2, the name space is working fine and return value ['root','key2']

I use react 15.6 and react-json-view 1.19.1

Any help is welcome

Best,

**Comment by zhousai1222** [comment]
+1

**Comment by mac-s-g** [comment]
I verified this is a bug.

**Comment by mac-s-g** [comment]
#321 resolves the issue.  once tests pass it will be published to 1.20.4

**Comment by mac-s-g** [comment]
heyoooooooo fix published to `1.20.4`
thanks everyone for contributing to the discussion :heart:
