### ISSUE TITLE
Coverage information in dist/main.js

### ISSUE THREAD

**Issue by Gelio** [mac-s-g/react-json-view#317]
Hey,

I upgraded to react-json-view@1.20.2 and for some reason, jest's coverage check started failing. After some debugging I found out that the `dist/main.js` file from `react-json-view` has something that resembles coverage information :exploding_head: 

![image](https://user-images.githubusercontent.com/889383/105510617-25608400-5ccf-11eb-8ff6-684ede4e7264.png)

I reckon it would be best if the coverage information was not included :slightly_smiling_face: I tried to take a look at the repo configuration but I did not find anything that would indicate invalid config.

Thanks for maintaining the library, by the way!

**Comment by mac-s-g** [comment]
haha fuck!

thanks for pointing this out.  There were some massive dependency updates between 1.19.x and 1.20.2.

I'll be working on damage control tomorrow to address issues coming from those changes.

this looks like an obvious screw up on my end... i clearly included coverage info with the assets published to npm.

I should have this resolved some time tomorrow.  I'll post an update when the update is being published.

thanks again for posting extra detail @Gelio !

**Comment by Gelio** [comment]
No worries 😄 take your time

I'm still wondering how the coverage info got into the bundle 🤔

**Comment by mac-s-g** [comment]
MR #318 will resolve this issue.
i had babel including the `istanbul` plugin for all environments.
the fix also cuts the build size in half.

once the MR is merged, i'll publish to npm at `1.20.3`

**Comment by mac-s-g** [comment]
that's been published.  thanks again @Gelio

**Comment by Gelio** [comment]
Awesome, thank you for a swift fix, and for explaining the issue :+1:
