### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by pm-mkorpar** [mac-s-g/react-json-view#330]
react-textarea-autosize  6.1.0  does not support react 17, is there any reason for not using a newer version?

`
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=0.14.0 <17.0.0" from react-textarea-autosize@6.1.0
npm ERR! node_modules/react-json-view/node_modules/react-textarea-autosize
npm ERR!   react-textarea-autosize@"^6.1.0" from react-json-view@1.21.1
npm ERR!   node_modules/react-json-view
npm ERR!     react-json-view@"^1.21.1" from the root project
`

**Comment by mac-s-g** [comment]
i'll take a look this weekend.
thanks for reporting the issue @pm-mkorpar

**Comment by silltho** [comment]
@mac-s-g any update on this. If you don't have time to look at this i could create a PR.

**Comment by vizardkill** [comment]
and React 17.0.1

**Comment by mac-s-g** [comment]
sorry guys i snoozed on this.  i'm in the process of posting a pr that will include an upgrade of `react-textarea-autosize` from `^6.1.0` to `^8.3.2`.

`8.3.2` includes `react >= 17` as a peer dependency, so this should solve the issue.

**Comment by mac-s-g** [comment]
pr linked above.  as soon as tests pass, i'll merge and publish to npm @ `1.21.2`.

**Comment by mac-s-g** [comment]
published to npm: `react-json-view@1.21.2`
