### ISSUE TITLE
Support for Symbol

### ISSUE THREAD

**Issue by fred8617** [mac-s-g/react-json-view#343]
Symbol(123).toString() as a key?

**Comment by mac-s-g** [comment]
?

**Comment by fred8617** [comment]
@mac-s-g sorry,i did't describe clearly
[https://fred8617.github.io/react-sandbox/](https://fred8617.github.io/react-sandbox/)
at this demo page , you can see right bottom ,and the field which is typeof==='Symbol' is not show in rjv component
