### ISSUE TITLE
Vulnerability with dependency ua-parser-js

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [mac-s-g/react-json-view#370]
npm audit shows the vulnerabilities with dependency of react-json-view

High            Regular Expression Denial of Service

  Package         ua-parser-js

  Dependency of   react-json-view

  Path            react-json-view > flux > fbemitter > fbjs > ua-parser-js

  More info       https://npmjs.com/advisories/1679

  High            Regular Expression Denial of Service

  Package         ua-parser-js

  Dependency of   react-json-view

  Path            react-json-view > flux > fbjs > ua-parser-js

  More info       https://npmjs.com/advisories/1679

**Comment by Smolations** [comment]
Isn't this a dupe of #359 ? It's like, 5 issues down. Shoulda checked first, my dude.
