### ISSUE TITLE
Consider typescript users

### ISSUE THREAD

**Issue by maybesmurf** [mac-s-g/react-json-view#404]
It's 2022 why is there no typescript types? Add typings

**Comment by christopher-caldwell** [comment]
![Screen Shot 2022-05-07 at 10 06 19 AM](https://user-images.githubusercontent.com/62559469/167260111-9dce17b1-2026-422d-b047-5cb21677d195.png)

The types are already included.

![Screen Shot 2022-05-07 at 10 07 08 AM](https://user-images.githubusercontent.com/62559469/167260139-903dcf59-e297-4c83-9297-63d76eccff6d.png)
