### ISSUE TITLE
dist/main.js contains source maps

### ISSUE THREAD

**Issue by bcronin** [mac-s-g/react-json-view#51]
(First off, thanks for the great React component!)

I'm not a webpack expert but it looks like the NPM distributed `dist/main.js` contains embedded source maps for all/many of the dependencies (or more generally, it looks to be a debug build).  It's difficult to use `react-json-view` in a production project _of my own_ because it pulls in that debugging information. Webpack doesn't optimize it back out so my production bundle ends up being 3+ MB larger, making it unusable.

**Comment by mac-s-g** [comment]
thanks for pointing this out.  I'll investigate today.

**Comment by mac-s-g** [comment]
opened #52 which removes source map from production builds.  I'll merge momentarily, and publish to npm at version 1.8.2

`dist/main.js` is down to around 350kb.  I think there is still room for optimization, but I'll get this out for now.

thanks again for pointing this out!
