### ISSUE TITLE
Failed context type

### ISSUE THREAD

**Issue by jsteenkamp** [mac-s-g/react-json-view#53]
I'm not sure if this is caused by this component directly, however it is only shown when adding the component in project with React +15.4. Possibly 3rd party package used by this component is causing this.

Warning: Failed context type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at [http://fb.me/use-check-prop-types](http://fb.me/use-check-prop-types)

**Comment by mac-s-g** [comment]
Thanks for bringing this up.  It's coming from a dependency.  I'll try to dig a little deeper and track it down.

**Comment by mac-s-g** [comment]
found the source and resolved.

**Comment by gernotlabahn** [comment]
Could you please publish a new version to the registry since the current one seems not to include this fix

**Comment by mac-s-g** [comment]
strange.  the development build doesn't log the propTypes error, but the production build does.
I'll re-open and continue to debug.

**Comment by mac-s-g** [comment]
the error is originating from `react-icon-base` through the `react-icons` dependency.

the issue was supposed to be fixed with react-icons v.2.2.5, but the error still appears with production builds.

I commented here: https://github.com/gorangajic/react-icon-base/issues/20

**Comment by mac-s-g** [comment]
i went ahead and resolved this by removing the react-icons dependency and creating my own icon components.

positives:

no more warnings!
smaller overall bundle size without react-icons dependency
negatives:

takes a little longer to add a new icons (though i'm not sure i'll need any more than what's currently being used)
pr is here: #77

I'll comment and close once that's merged and published

**Comment by mac-s-g** [comment]
merged and published 

+ react-json-view@1.10.5

really glad that's done.
