### ISSUE TITLE
Uncaught Error: Minified React error #31; visit

### ISSUE THREAD

**Issue by cesarve77** [mac-s-g/react-json-view#54]
Wonderfull tool. Thanks

I got error with 

`<ReactJson src={[new Date(),new Date()]} />`

I I really have performance problems if I display several ReactJson components (250 components with small objects)

thanks and sorry for my english

**Comment by mac-s-g** [comment]
Thanks, I have to add support for dates.  I'll update this issue when I get a PR up.

What rjv version are you using?  I removed a bunch of debug output from the build at v 1.8.2.  using that version or later could help performance?

**Comment by cesarve77** [comment]
I'm using the last version

2017-05-30 17:59 GMT+10:00 Mac Gainor <notifications@github.com>:

**Comment by mac-s-g** [comment]
added support for dates
