### ISSUE TITLE
Should not render functions from prototype in array

### ISSUE THREAD

**Issue by mindriven** [mac-s-g/react-json-view#59]
Hi there,
I've tried to use your great looking component, and I've encountered the following problem:
![problem](https://user-images.githubusercontent.com/4957654/26921226-a3247b42-4c3b-11e7-8d64-cd4b05295b67.png)

It looks like you're rendering each property in object using for-in loop, this leads to every method from the prototype to get rendered on each occurrence of given type as well (in my example Array type). I mean here: https://github.com/mac-s-g/react-json-view/blob/master/src/js/components/DataTypes/Object.js#L191

Any chance for fix?

**Comment by mac-s-g** [comment]
great feedback! thanks for investigating.
That is probably related to the performance problems that @cesarve77 mentioned in #54 .
I'll try to get a PR up this weekend.

**Comment by mac-s-g** [comment]
I misunderstood the issue at first, but I have a fix ready to go.  I'll merge and publish later today.
thanks again for pointing it out.

**Comment by mac-s-g** [comment]
I fixed this and published react-json-view@1.8.4
https://www.npmjs.com/package/react-json-view
