### ISSUE TITLE
feature request: expand/collapse large strings

### ISSUE THREAD

**Issue by vagyriag** [mac-s-g/react-json-view#60]
Hi,

I'm using rjv to inspect some collections of complex objects, so I can verify the structure of the data.
Sometimes the content has a large paragraph of text so I have to scroll a lot, and I don't really care for the text, just want to know it's there.

I think there could be a way to expand/collapse large strings, when it's collapsed it only shows the initial chars but can be expanded to reveal the entire content.

What do you think? Would you accept a PR for this?
Would love to contribute.

**Comment by mac-s-g** [comment]
I love this idea!

could we tie it into a prop?

like: `collapseStringsWithLength`.  Default could be `false`, meaning "dont collapse".  But an integer could specify a length after which a string is collapsed.  EG:  a prop value of `100` means strings longer than 100 chars will be collapsed with elipsis.

collapsed strings could be displayed as the first `collapseStringsWithLength` chars followed by an elipsis that you could click to expand.  So for `collapseStringsWithLength = 20`, you might see:
`string "this is a long strin..."`

i think that would be pretty neat.  OF COURSE, if you want to contribute, you can take it in whatever direction you want to best meet your needs!  I'm happy to review and merge if it looks good.

let me know if I can help improve documentation on how to contribute - or give some information about where to look for certain methods.

**Comment by vagyriag** [comment]
I'm glad you like it!

yes. I though something similar.
maybe the prop name should be more like ```collapseStringsAfterLenght```? 
that way is clear that it's a > operator

I have never contributed on a project on github, so if you think there's something not so obvious to me or any recommendation I would appreciate it.

**Comment by mac-s-g** [comment]
that property name sounds good to me.

I'd recommend developing within a docker container.  I documented the development process in the README.

I also request that you write tests for any new content.

**Comment by vagyriag** [comment]
What could we use to collapse the string after it has been expanded? 
I tried the CircleMinus but didn't like it very much in this context (without the accompanying CirclePlus)
Maybe a backspace? ←⇐
Or an x in a circle?
I don't know

**Comment by mac-s-g** [comment]
you could just make the string container clickable when that prop is not false.
it will probably look good without an icon.

**Comment by mac-s-g** [comment]
I just published react-json-view v.19.0.0

The latest version includes the `collapseStringsAfterLength` attribute which defaults to false.

You can pass an integer in to collapse strings at a particular length.  Collapsed strings will be followed with an ellipsis indicator (see README props table for documentation).

Click on the string to expand/collapse.

There's a demo here: https://mac-s-g.github.io/react-json-view/example/example.html

Checkout the first string in the first example.

I'm gonna close this issue, but feel free to add feedback if you'd like to see different behavior!
pr is here if you're interested in reviewing: #62
