### ISSUE TITLE
Feature Request: Collapse default by depth

### ISSUE THREAD

**Issue by shanielh** [mac-s-g/react-json-view#66]
Hi Again :smile: 

I would like to collapse by default until a certain depth of the JSON tree.

Suggestion: Change `collapsed` prop to allow numbers, and if a number is inserted - Expand until the given depth, for example : 0 - collapse all (including root), 1 - expand root, 2 - expand root and direct descendants, etc...

**Comment by mac-s-g** [comment]
This is a great idea!  I'll update this issue when I have a PR.

**Comment by shanielh** [comment]
Hi @mac-s-g, I see that it's delaying... Do you want me to pull request?

**Comment by mac-s-g** [comment]
sorry about the delay!

The pr is here: #69  

I'll merge and publish once tests all pass

**Comment by mac-s-g** [comment]
However, I'm always open to reviewing pr's if you're interested in contributing :+1:

**Comment by mac-s-g** [comment]
published:
react-json-view@1.10.2

let me know how that works for you
