### ISSUE TITLE
Calling PropTypes validators directly is not supported by the `prop-types` package

### ISSUE THREAD

**Issue by JerryCauser** [mac-s-g/react-json-view#67]
Some of `{rjv}` dependency use deprecated code. You can repeat it even in your own example.
I tried to find that dep, but l it was unsuccessful.

I wanna use you lib, but I can't use libs with deprecations in prod.
Have any idea where is the trouble?
![image](https://user-images.githubusercontent.com/5141037/27451950-812257e4-5799-11e7-84a5-373281226758.png)

**Comment by mac-s-g** [comment]
yea, it's tough to track down the culprit without a source map enabled.

I built with a source map in a dev environment and tracked it down to the react-icons dependency.

i posed a comment on their issue here: https://github.com/gorangajic/react-icon-base/issues/20

I'll try to get more info and update here.

**Comment by mac-s-g** [comment]
i went ahead and resolved this by removing the react-icons dependency and creating my own icon components.

*positives:*
* no more warnings!
* smaller overall bundle size without react-icons dependency

*negatives:*
* takes a little longer to add a new icons (though i'm not sure i'll need any more than what's currently being used)

pr is here: #77 

I'll comment and close once that's merged and published

**Comment by mac-s-g** [comment]
merged and published

react-json-view@1.10.5

really glad that's done.

**Comment by JerryCauser** [comment]
Thank you, man!
