### ISSUE TITLE
Returning false from `onEdit` or `onDelete` does not prevent the edit from happening.

### ISSUE THREAD

**Issue by joeblubaugh** [mac-s-g/react-json-view#72]
I've replaced my `onEdit` and `onDelete` functions with ones that only call "return false;" and I see that they're called and return false. However, the new src object is replaced with the edited one anyway.

This isn't true of `onAdd`. If I return false there, the item is not added, and the "New" window stays up. Is there a way to dismiss it and show an error instead?

**Comment by mac-s-g** [comment]
yea, those features are pretty new, so I can take another look at the behavior when returning false.

Ideally, the user can treat `onAdd`, `onDelete` and `onEdit` as validation functions - and `return false` to prevent changes from being made.

That would be useful if you wanted to make sure a particular field can only have an integer value, for example.

Error messages are not (yet?) supported though, so the `returning false` might be confusing to the user.

In any case, i'll investigate the current behavior.  Hopefully I can do that this weekend.

**Comment by joeblubaugh** [comment]
Thank you!

**Comment by mac-s-g** [comment]
sorry I haven't gotten to this yet.  This issue is the next one on my list.

**Comment by mac-s-g** [comment]
just posted #80 which does the following:

onEdit, onAdd, and onDelete do not succeed when the associated callback returns false.

when a callback returns false, a "validation error" indicator pops up in the top right of the RJV container.

I'll update when that's merged and published.

**Comment by mac-s-g** [comment]
published: react-json-view@1.10.8

let me know what you think.

**Comment by mac-s-g** [comment]
i found a bug in 1.10.8.

published 1.10.9 with a fix
