### ISSUE TITLE
Editing a value for the first time does not show the value in the "edit" block

### ISSUE THREAD

**Issue by joeblubaugh** [mac-s-g/react-json-view#73]
Steps to repro:
- Load a JS object as src on ReactJSON
- Click a field to edit. Note that the textarea is empty with the placeholder "update this value"
- Put the new value in and update.
- Click the same field to edit again. Note that the textarea is populated with the new value.

When running this in the debugger, I noticed that the `state.editValue === ""` rather than the string value I would expect.

Thanks for the maintenance work!

**Comment by mac-s-g** [comment]
what is the expected behavior?

do you think the edit-box should always pre-populate with current value ?

**Comment by mac-s-g** [comment]
posted #79 

that also includes collapsible functions and tests - but edit box will always pre-populate with the current variable value.

I'll update when that's merged and published

**Comment by mac-s-g** [comment]
merged and published
