### ISSUE TITLE
Allow changing "root" object name.

### ISSUE THREAD

**Issue by shanielh** [mac-s-g/react-json-view#74]
I have an object that looks like this : 

![screenshot from 2017-07-04 10 08 45](https://user-images.githubusercontent.com/746471/27818973-c6519d38-60a0-11e7-9ab5-b8b529e93c22.png)

I would like to remove the "root" object name so it'll look more like the source json : 

```json
{
   "time":"7/4/2017, 10:07:00 A ...",
   "created_at":"Tue Jul 04 07:06:58 ...",
   "id":882133618931286000,
   "id_str":"882133618931286016",
   "text":"https://t.co/6S1JWqQ ...",
   "display_text_range":[...],
   "source":"....",
   "truncated":false,
   "in_reply_to_status_id":null,
   "in_reply_to_status_id_str":null,
   "in_reply_to_user_id":null,
   "in_reply_to_user_id_str":null,
   "in_reply_to_screen_name":null
}
```

**Comment by mac-s-g** [comment]
just posted #78

that allows you to pass `false` or `null` to the `name` property.

when you pass one of those two values, you'll get something like this:

![root-false](https://user-images.githubusercontent.com/4097374/27991861-10eec6d6-6439-11e7-884f-a795acd5f482.png)

**Comment by mac-s-g** [comment]
published!

+ react-json-view@1.10.6

let me know what you think

**Comment by shanielh** [comment]
Amazing. Thanks 👍🏼
