### ISSUE TITLE
Style Request: Edit box should fit input size

### ISSUE THREAD

**Issue by mac-s-g** [mac-s-g/react-json-view#89]
The default height of the text-area is too tall for single line inputs. The text-area should be the same size as the input, and grow as needed. This would also eliminate any jank seen when toggling edit mode.

https://www.reddit.com/r/reactjs/comments/6qz2ig/json_viewer_with_editor/

**Comment by wangzuo** [comment]
you may try [react-input-autosize](https://github.com/JedWatson/react-input-autosize)

**Comment by mac-s-g** [comment]
react-input-autosize isn't working well because it doesn't work well.  I'm trying out [react-textarea-autosize](https://www.npmjs.com/package/react-textarea-autosize) now.

**Comment by mac-s-g** [comment]
react-textarea-autosize is an improvement.

as long as it doesn't increase the size of my build too much, i'll add this feature.

**Comment by mac-s-g** [comment]
merged #114 and published to npm under [react-json-view@1.12.4](https://www.npmjs.com/package/react-json-view)

`onEdit` input scales vertically with input.

I also deployed the updates to the [demo](https://mac-s-g.github.io/react-json-view/demo/dist/).
