### ISSUE TITLE
Custom Validation Error Support

### ISSUE THREAD

**Issue by novemberde** [mac-s-g/react-json-view#90]
There's only 'validation error' if src data is not valid.
I want to put custom message make sure to our country's client as our language.
So, custom error message is necessary to notify validation error for other language.

Thank you for considering my opinion :)

**Comment by mac-s-g** [comment]
great idea!  i will add this

**Comment by mac-s-g** [comment]
this is available via the `validationMessage` prop.
you can update that prop with each distinct validation failure if you'd like.
default is still "Validation Failure".

merged with #101 and published to npm under v.10.11.7

let me know if you have any issues!
