### ISSUE TITLE
Add collapse callback for render

### ISSUE THREAD

**Issue by StupidHod** [mac-s-g/react-json-view#92]
Hi, I'm a fans of 'react-json-view', it's very cool and beautiful.

But the chrome don't respond when I want to render huge object. I think it's will be great to add a callback to decide whether to collapse a node depends on the index and the depth of the node.

**Comment by appsmehta** [comment]
+1. Chrome freezes when the object is too big. Also,  I understand that we have a depthCollapse option, but a button to toggle expansion of all records or first few records from a depth level would be really helpful.

**Comment by mac-s-g** [comment]
try out the latest version (v.1.11.8)

there is a significant performance improvement.

does chrome still freeze up?

**Comment by mac-s-g** [comment]
there have been some significant performance improvements since this was posted.  

I'm gonna close for now.  Please let me know if you're still experiencing issues and I'll be happy to re-open.
